name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'



      - name: Install specific version of MiniZinc
        run: |
          wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.7.5/MiniZincIDE-2.7.5-bundle-linux-x86_64.tgz
          tar -xvzf MiniZincIDE-2.7.5-bundle-linux-x86_64.tgz
          sudo mv MiniZincIDE-2.7.5-bundle-linux-x86_64 /opt/minizinc
          echo "PATH=/opt/minizinc/bin:$PATH" >> $GITHUB_ENV

      - name: Add MiniZinc to PATH
        run: echo "PATH=/usr/bin:$PATH" >> $GITHUB_ENV
      
      - name: Verify MiniZinc Installation
        run: minizinc --version

      - name: Install missing library
        run: sudo apt-get install -y libegl1

      # You can test your matrix by printing the current Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV 
      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests --doctest-modules --junitxml=junit/test-results.xml
